project:
  type: book
  output-dir: _book

book:
  title: "Лабораторная работа №1"
  subtitle: "Модель экспоненциального роста"
  author: "Ваше Имя"
  date: "2026-08-23"
  chapters:
    - index.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: true
    colorlinks: true

engine: julia
julia:
  exeflags: ["--project=../project"]
